- type: entity
  parent: BaseMachineCircuitboard
  id: MachineBluespaceHarvesterCircuitboard
  name: Bluespace Harvester board
  description: A machine board for a Bluespace Harvester
  components:
  - type: Sprite
    sprite: _CorvaxGoob/Bluespace/module.rsi
    state: bluespace
  - type: MachineBoard
    prototype: BluespaceHarvester
    stackRequirements:
      Glass: 15
      Steel: 15
      CableHV: 5
      BSCrystal: 4
  - type: Item
    size: Normal

- type: entity
  parent: BaseMachineCircuitboard
  id: MachineBluespaceTransitorCircuitboard
  name: bluespace T.R.A.N.S.I.T.O.R board
  description: A machine board for a bluespace T.R.A.N.S.I.T.O.R
  components:
  - type: Sprite
    sprite: Objects/Misc/module.rsi
    state: bluespacearray
  - type: MachineBoard
    prototype: BluespaceTransitor
    stackRequirements:
      Steel: 10
      CableHV: 30
      BSCrystal: 4
  - type: Item
    size: Normal

- type: entity
  id: PrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: document printer machine board
  description: A machine printed circuit board for an document printer
  components:
    - type: MachineBoard
      prototype: PrinterDoc
      stackRequirements:
        Manipulator: 4
        Glass: 1

- type: entity
  parent: BaseMachineCircuitboard
  id: StasisOperatingTableCircuitboard
  name: stasis operating table board
  description: A machine board for a stasis operating table.
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: StasisOperatingTable
    stackRequirements:
      Cable: 6
      Silver: 2
      Steel: 6
      Manipulator: 1

- type: entity
  parent: BaseMachineCircuitboard
  id: MachineMedipenRefillerCircuitboard
  name: medipen refiller board
  description: A machine board for a medipen refiller
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: MedipenRefiller
    stackRequirements:
      Manipulator: 5
    tagRequirements:
      GlassBeaker:
        amount: 3
        defaultPrototype: Beaker
  - type: Item
    size: Normal

- type: entity
  parent: BaseMachineCircuitboard
  id: QuantumTelepadMachineCircuitboard
  name: quantum telepad machine board
  description: A machine printed circuit board for a quantum telepad.
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: QuantumTelepad
    stackRequirements:
      Steel: 20
      Glass: 15
      Plasma: 10
      Manipulator: 2
  - type: Item
    size: Normal
